// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: testdata/protobuf/test.proto

package testpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EnumMessage contains an enum field
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_INACTIVE    Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_INACTIVE",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_INACTIVE":    2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_testdata_protobuf_test_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_testdata_protobuf_test_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_testdata_protobuf_test_proto_rawDescGZIP(), []int{0}
}

// BasicMessage is a simple message for testing basic types
type BasicMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Active        bool                   `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BasicMessage) Reset() {
	*x = BasicMessage{}
	mi := &file_testdata_protobuf_test_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BasicMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BasicMessage) ProtoMessage() {}

func (x *BasicMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protobuf_test_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BasicMessage.ProtoReflect.Descriptor instead.
func (*BasicMessage) Descriptor() ([]byte, []int) {
	return file_testdata_protobuf_test_proto_rawDescGZIP(), []int{0}
}

func (x *BasicMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BasicMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BasicMessage) GetActive() bool {
	if x != nil {
		return x.Active
	}
	return false
}

func (x *BasicMessage) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// NestedMessage contains a nested message
type NestedMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        *BasicMessage          `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NestedMessage) Reset() {
	*x = NestedMessage{}
	mi := &file_testdata_protobuf_test_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NestedMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NestedMessage) ProtoMessage() {}

func (x *NestedMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protobuf_test_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NestedMessage.ProtoReflect.Descriptor instead.
func (*NestedMessage) Descriptor() ([]byte, []int) {
	return file_testdata_protobuf_test_proto_rawDescGZIP(), []int{1}
}

func (x *NestedMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NestedMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *NestedMessage) GetAuthor() *BasicMessage {
	if x != nil {
		return x.Author
	}
	return nil
}

// ListMessage contains repeated fields
type ListMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Numbers       []int32                `protobuf:"varint,3,rep,packed,name=numbers,proto3" json:"numbers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMessage) Reset() {
	*x = ListMessage{}
	mi := &file_testdata_protobuf_test_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMessage) ProtoMessage() {}

func (x *ListMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protobuf_test_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMessage.ProtoReflect.Descriptor instead.
func (*ListMessage) Descriptor() ([]byte, []int) {
	return file_testdata_protobuf_test_proto_rawDescGZIP(), []int{2}
}

func (x *ListMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListMessage) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ListMessage) GetNumbers() []int32 {
	if x != nil {
		return x.Numbers
	}
	return nil
}

// MapMessage contains map fields
type MapMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Scores        map[string]int32       `protobuf:"bytes,3,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapMessage) Reset() {
	*x = MapMessage{}
	mi := &file_testdata_protobuf_test_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapMessage) ProtoMessage() {}

func (x *MapMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protobuf_test_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapMessage.ProtoReflect.Descriptor instead.
func (*MapMessage) Descriptor() ([]byte, []int) {
	return file_testdata_protobuf_test_proto_rawDescGZIP(), []int{3}
}

func (x *MapMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MapMessage) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MapMessage) GetScores() map[string]int32 {
	if x != nil {
		return x.Scores
	}
	return nil
}

// AllTypesMessage tests various types
type AllTypesMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Int32Field    int32                  `protobuf:"varint,1,opt,name=int32_field,json=int32Field,proto3" json:"int32_field,omitempty"`
	Int64Field    int64                  `protobuf:"varint,2,opt,name=int64_field,json=int64Field,proto3" json:"int64_field,omitempty"`
	Uint32Field   uint32                 `protobuf:"varint,3,opt,name=uint32_field,json=uint32Field,proto3" json:"uint32_field,omitempty"`
	Uint64Field   uint64                 `protobuf:"varint,4,opt,name=uint64_field,json=uint64Field,proto3" json:"uint64_field,omitempty"`
	Sint32Field   int32                  `protobuf:"zigzag32,5,opt,name=sint32_field,json=sint32Field,proto3" json:"sint32_field,omitempty"`
	Sint64Field   int64                  `protobuf:"zigzag64,6,opt,name=sint64_field,json=sint64Field,proto3" json:"sint64_field,omitempty"`
	Fixed32Field  uint32                 `protobuf:"fixed32,7,opt,name=fixed32_field,json=fixed32Field,proto3" json:"fixed32_field,omitempty"`
	Fixed64Field  uint64                 `protobuf:"fixed64,8,opt,name=fixed64_field,json=fixed64Field,proto3" json:"fixed64_field,omitempty"`
	Sfixed32Field int32                  `protobuf:"fixed32,9,opt,name=sfixed32_field,json=sfixed32Field,proto3" json:"sfixed32_field,omitempty"`
	Sfixed64Field int64                  `protobuf:"fixed64,10,opt,name=sfixed64_field,json=sfixed64Field,proto3" json:"sfixed64_field,omitempty"`
	FloatField    float32                `protobuf:"fixed32,11,opt,name=float_field,json=floatField,proto3" json:"float_field,omitempty"`
	DoubleField   float64                `protobuf:"fixed64,12,opt,name=double_field,json=doubleField,proto3" json:"double_field,omitempty"`
	BoolField     bool                   `protobuf:"varint,13,opt,name=bool_field,json=boolField,proto3" json:"bool_field,omitempty"`
	StringField   string                 `protobuf:"bytes,14,opt,name=string_field,json=stringField,proto3" json:"string_field,omitempty"`
	BytesField    []byte                 `protobuf:"bytes,15,opt,name=bytes_field,json=bytesField,proto3" json:"bytes_field,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllTypesMessage) Reset() {
	*x = AllTypesMessage{}
	mi := &file_testdata_protobuf_test_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTypesMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTypesMessage) ProtoMessage() {}

func (x *AllTypesMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protobuf_test_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTypesMessage.ProtoReflect.Descriptor instead.
func (*AllTypesMessage) Descriptor() ([]byte, []int) {
	return file_testdata_protobuf_test_proto_rawDescGZIP(), []int{4}
}

func (x *AllTypesMessage) GetInt32Field() int32 {
	if x != nil {
		return x.Int32Field
	}
	return 0
}

func (x *AllTypesMessage) GetInt64Field() int64 {
	if x != nil {
		return x.Int64Field
	}
	return 0
}

func (x *AllTypesMessage) GetUint32Field() uint32 {
	if x != nil {
		return x.Uint32Field
	}
	return 0
}

func (x *AllTypesMessage) GetUint64Field() uint64 {
	if x != nil {
		return x.Uint64Field
	}
	return 0
}

func (x *AllTypesMessage) GetSint32Field() int32 {
	if x != nil {
		return x.Sint32Field
	}
	return 0
}

func (x *AllTypesMessage) GetSint64Field() int64 {
	if x != nil {
		return x.Sint64Field
	}
	return 0
}

func (x *AllTypesMessage) GetFixed32Field() uint32 {
	if x != nil {
		return x.Fixed32Field
	}
	return 0
}

func (x *AllTypesMessage) GetFixed64Field() uint64 {
	if x != nil {
		return x.Fixed64Field
	}
	return 0
}

func (x *AllTypesMessage) GetSfixed32Field() int32 {
	if x != nil {
		return x.Sfixed32Field
	}
	return 0
}

func (x *AllTypesMessage) GetSfixed64Field() int64 {
	if x != nil {
		return x.Sfixed64Field
	}
	return 0
}

func (x *AllTypesMessage) GetFloatField() float32 {
	if x != nil {
		return x.FloatField
	}
	return 0
}

func (x *AllTypesMessage) GetDoubleField() float64 {
	if x != nil {
		return x.DoubleField
	}
	return 0
}

func (x *AllTypesMessage) GetBoolField() bool {
	if x != nil {
		return x.BoolField
	}
	return false
}

func (x *AllTypesMessage) GetStringField() string {
	if x != nil {
		return x.StringField
	}
	return ""
}

func (x *AllTypesMessage) GetBytesField() []byte {
	if x != nil {
		return x.BytesField
	}
	return nil
}

// OptionalMessage contains optional fields
type OptionalMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Age           *int32                 `protobuf:"varint,3,opt,name=age,proto3,oneof" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionalMessage) Reset() {
	*x = OptionalMessage{}
	mi := &file_testdata_protobuf_test_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionalMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionalMessage) ProtoMessage() {}

func (x *OptionalMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protobuf_test_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionalMessage.ProtoReflect.Descriptor instead.
func (*OptionalMessage) Descriptor() ([]byte, []int) {
	return file_testdata_protobuf_test_proto_rawDescGZIP(), []int{5}
}

func (x *OptionalMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OptionalMessage) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *OptionalMessage) GetAge() int32 {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return 0
}

type EnumMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        Status                 `protobuf:"varint,2,opt,name=status,proto3,enum=testpb.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumMessage) Reset() {
	*x = EnumMessage{}
	mi := &file_testdata_protobuf_test_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumMessage) ProtoMessage() {}

func (x *EnumMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protobuf_test_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumMessage.ProtoReflect.Descriptor instead.
func (*EnumMessage) Descriptor() ([]byte, []int) {
	return file_testdata_protobuf_test_proto_rawDescGZIP(), []int{6}
}

func (x *EnumMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *EnumMessage) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

// OneofMessage contains oneof fields
type OneofMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*OneofMessage_Text
	//	*OneofMessage_Number
	//	*OneofMessage_Flag
	Value         isOneofMessage_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofMessage) Reset() {
	*x = OneofMessage{}
	mi := &file_testdata_protobuf_test_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofMessage) ProtoMessage() {}

func (x *OneofMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protobuf_test_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofMessage.ProtoReflect.Descriptor instead.
func (*OneofMessage) Descriptor() ([]byte, []int) {
	return file_testdata_protobuf_test_proto_rawDescGZIP(), []int{7}
}

func (x *OneofMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OneofMessage) GetValue() isOneofMessage_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OneofMessage) GetText() string {
	if x != nil {
		if x, ok := x.Value.(*OneofMessage_Text); ok {
			return x.Text
		}
	}
	return ""
}

func (x *OneofMessage) GetNumber() int32 {
	if x != nil {
		if x, ok := x.Value.(*OneofMessage_Number); ok {
			return x.Number
		}
	}
	return 0
}

func (x *OneofMessage) GetFlag() bool {
	if x != nil {
		if x, ok := x.Value.(*OneofMessage_Flag); ok {
			return x.Flag
		}
	}
	return false
}

type isOneofMessage_Value interface {
	isOneofMessage_Value()
}

type OneofMessage_Text struct {
	Text string `protobuf:"bytes,2,opt,name=text,proto3,oneof"`
}

type OneofMessage_Number struct {
	Number int32 `protobuf:"varint,3,opt,name=number,proto3,oneof"`
}

type OneofMessage_Flag struct {
	Flag bool `protobuf:"varint,4,opt,name=flag,proto3,oneof"`
}

func (*OneofMessage_Text) isOneofMessage_Value() {}

func (*OneofMessage_Number) isOneofMessage_Value() {}

func (*OneofMessage_Flag) isOneofMessage_Value() {}

// OneofWithMessageMessage contains oneof with nested message
type OneofWithMessageMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Types that are valid to be assigned to Data:
	//
	//	*OneofWithMessageMessage_Description
	//	*OneofWithMessageMessage_User
	Data          isOneofWithMessageMessage_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofWithMessageMessage) Reset() {
	*x = OneofWithMessageMessage{}
	mi := &file_testdata_protobuf_test_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofWithMessageMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofWithMessageMessage) ProtoMessage() {}

func (x *OneofWithMessageMessage) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_protobuf_test_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofWithMessageMessage.ProtoReflect.Descriptor instead.
func (*OneofWithMessageMessage) Descriptor() ([]byte, []int) {
	return file_testdata_protobuf_test_proto_rawDescGZIP(), []int{8}
}

func (x *OneofWithMessageMessage) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OneofWithMessageMessage) GetData() isOneofWithMessageMessage_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OneofWithMessageMessage) GetDescription() string {
	if x != nil {
		if x, ok := x.Data.(*OneofWithMessageMessage_Description); ok {
			return x.Description
		}
	}
	return ""
}

func (x *OneofWithMessageMessage) GetUser() *BasicMessage {
	if x != nil {
		if x, ok := x.Data.(*OneofWithMessageMessage_User); ok {
			return x.User
		}
	}
	return nil
}

type isOneofWithMessageMessage_Data interface {
	isOneofWithMessageMessage_Data()
}

type OneofWithMessageMessage_Description struct {
	Description string `protobuf:"bytes,2,opt,name=description,proto3,oneof"`
}

type OneofWithMessageMessage_User struct {
	User *BasicMessage `protobuf:"bytes,3,opt,name=user,proto3,oneof"`
}

func (*OneofWithMessageMessage_Description) isOneofWithMessageMessage_Data() {}

func (*OneofWithMessageMessage_User) isOneofWithMessageMessage_Data() {}

var File_testdata_protobuf_test_proto protoreflect.FileDescriptor

const file_testdata_protobuf_test_proto_rawDesc = "" +
	"\n" +
	"\x1ctestdata/protobuf/test.proto\x12\x06testpb\"`\n" +
	"\fBasicMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06active\x18\x03 \x01(\bR\x06active\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\"c\n" +
	"\rNestedMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12,\n" +
	"\x06author\x18\x03 \x01(\v2\x14.testpb.BasicMessageR\x06author\"K\n" +
	"\vListMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12\x18\n" +
	"\anumbers\x18\x03 \x03(\x05R\anumbers\"\x82\x02\n" +
	"\n" +
	"MapMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x126\n" +
	"\x06labels\x18\x02 \x03(\v2\x1e.testpb.MapMessage.LabelsEntryR\x06labels\x126\n" +
	"\x06scores\x18\x03 \x03(\v2\x1e.testpb.MapMessage.ScoresEntryR\x06scores\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vScoresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"\x9e\x04\n" +
	"\x0fAllTypesMessage\x12\x1f\n" +
	"\vint32_field\x18\x01 \x01(\x05R\n" +
	"int32Field\x12\x1f\n" +
	"\vint64_field\x18\x02 \x01(\x03R\n" +
	"int64Field\x12!\n" +
	"\fuint32_field\x18\x03 \x01(\rR\vuint32Field\x12!\n" +
	"\fuint64_field\x18\x04 \x01(\x04R\vuint64Field\x12!\n" +
	"\fsint32_field\x18\x05 \x01(\x11R\vsint32Field\x12!\n" +
	"\fsint64_field\x18\x06 \x01(\x12R\vsint64Field\x12#\n" +
	"\rfixed32_field\x18\a \x01(\aR\ffixed32Field\x12#\n" +
	"\rfixed64_field\x18\b \x01(\x06R\ffixed64Field\x12%\n" +
	"\x0esfixed32_field\x18\t \x01(\x0fR\rsfixed32Field\x12%\n" +
	"\x0esfixed64_field\x18\n" +
	" \x01(\x10R\rsfixed64Field\x12\x1f\n" +
	"\vfloat_field\x18\v \x01(\x02R\n" +
	"floatField\x12!\n" +
	"\fdouble_field\x18\f \x01(\x01R\vdoubleField\x12\x1d\n" +
	"\n" +
	"bool_field\x18\r \x01(\bR\tboolField\x12!\n" +
	"\fstring_field\x18\x0e \x01(\tR\vstringField\x12\x1f\n" +
	"\vbytes_field\x18\x0f \x01(\fR\n" +
	"bytesField\"b\n" +
	"\x0fOptionalMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x15\n" +
	"\x03age\x18\x03 \x01(\x05H\x01R\x03age\x88\x01\x01B\a\n" +
	"\x05_nameB\x06\n" +
	"\x04_age\"E\n" +
	"\vEnumMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12&\n" +
	"\x06status\x18\x02 \x01(\x0e2\x0e.testpb.StatusR\x06status\"m\n" +
	"\fOneofMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x04text\x18\x02 \x01(\tH\x00R\x04text\x12\x18\n" +
	"\x06number\x18\x03 \x01(\x05H\x00R\x06number\x12\x14\n" +
	"\x04flag\x18\x04 \x01(\bH\x00R\x04flagB\a\n" +
	"\x05value\"\x81\x01\n" +
	"\x17OneofWithMessageMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\"\n" +
	"\vdescription\x18\x02 \x01(\tH\x00R\vdescription\x12*\n" +
	"\x04user\x18\x03 \x01(\v2\x14.testpb.BasicMessageH\x00R\x04userB\x06\n" +
	"\x04data*H\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x13\n" +
	"\x0fSTATUS_INACTIVE\x10\x02B3Z1github.com/hamba/avro/v2/testdata/protobuf;testpbb\x06proto3"

var (
	file_testdata_protobuf_test_proto_rawDescOnce sync.Once
	file_testdata_protobuf_test_proto_rawDescData []byte
)

func file_testdata_protobuf_test_proto_rawDescGZIP() []byte {
	file_testdata_protobuf_test_proto_rawDescOnce.Do(func() {
		file_testdata_protobuf_test_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_testdata_protobuf_test_proto_rawDesc), len(file_testdata_protobuf_test_proto_rawDesc)))
	})
	return file_testdata_protobuf_test_proto_rawDescData
}

var file_testdata_protobuf_test_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_testdata_protobuf_test_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_testdata_protobuf_test_proto_goTypes = []any{
	(Status)(0),                     // 0: testpb.Status
	(*BasicMessage)(nil),            // 1: testpb.BasicMessage
	(*NestedMessage)(nil),           // 2: testpb.NestedMessage
	(*ListMessage)(nil),             // 3: testpb.ListMessage
	(*MapMessage)(nil),              // 4: testpb.MapMessage
	(*AllTypesMessage)(nil),         // 5: testpb.AllTypesMessage
	(*OptionalMessage)(nil),         // 6: testpb.OptionalMessage
	(*EnumMessage)(nil),             // 7: testpb.EnumMessage
	(*OneofMessage)(nil),            // 8: testpb.OneofMessage
	(*OneofWithMessageMessage)(nil), // 9: testpb.OneofWithMessageMessage
	nil,                             // 10: testpb.MapMessage.LabelsEntry
	nil,                             // 11: testpb.MapMessage.ScoresEntry
}
var file_testdata_protobuf_test_proto_depIdxs = []int32{
	1,  // 0: testpb.NestedMessage.author:type_name -> testpb.BasicMessage
	10, // 1: testpb.MapMessage.labels:type_name -> testpb.MapMessage.LabelsEntry
	11, // 2: testpb.MapMessage.scores:type_name -> testpb.MapMessage.ScoresEntry
	0,  // 3: testpb.EnumMessage.status:type_name -> testpb.Status
	1,  // 4: testpb.OneofWithMessageMessage.user:type_name -> testpb.BasicMessage
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_testdata_protobuf_test_proto_init() }
func file_testdata_protobuf_test_proto_init() {
	if File_testdata_protobuf_test_proto != nil {
		return
	}
	file_testdata_protobuf_test_proto_msgTypes[5].OneofWrappers = []any{}
	file_testdata_protobuf_test_proto_msgTypes[7].OneofWrappers = []any{
		(*OneofMessage_Text)(nil),
		(*OneofMessage_Number)(nil),
		(*OneofMessage_Flag)(nil),
	}
	file_testdata_protobuf_test_proto_msgTypes[8].OneofWrappers = []any{
		(*OneofWithMessageMessage_Description)(nil),
		(*OneofWithMessageMessage_User)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_testdata_protobuf_test_proto_rawDesc), len(file_testdata_protobuf_test_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_protobuf_test_proto_goTypes,
		DependencyIndexes: file_testdata_protobuf_test_proto_depIdxs,
		EnumInfos:         file_testdata_protobuf_test_proto_enumTypes,
		MessageInfos:      file_testdata_protobuf_test_proto_msgTypes,
	}.Build()
	File_testdata_protobuf_test_proto = out.File
	file_testdata_protobuf_test_proto_goTypes = nil
	file_testdata_protobuf_test_proto_depIdxs = nil
}
